<div align="center">
  <img src="./assets/header.svg" width="100%" alt="Jeevan Varghese, senior data and AI engineer. An animated workflow graph moves data from ingestion through Spark and Temporal into Cassandra, Neo4j and a group of AI agents.">
</div>

<br>

I build the plumbing that data and AI agents run on: distributed pipelines, workflow engines that survive failure, and backends that keep many tenants apart. Senior data and AI engineer at **Experion Technologies**, based in Alappuzha, Kerala. When the builds are green, I paint.

### Running right now

- Distributed data pipelines, orchestration architectures and local-first AI tooling
- Microservices, event-driven backends and multi-tenant container orchestration
- Relational and graph data modeling, from PostgreSQL schemas to Neo4j knowledge graphs
- Writing on the blog about Python for data engineering

### Stack

<img src="./assets/stack.svg" width="100%" alt="Tech stack. Data and orchestration: Python, Apache Spark, Cassandra, Temporal, PostgreSQL, Neo4j. AI and backends: LangGraph, FastAPI, Docker, Traefik, GitHub Actions.">

### Shipped

<p>
  <a href="https://github.com/Jeevanvsan/sharejeeni"><img src="./assets/card-sharejeeni.svg" width="49%" alt="sharejeeni: Python package that downloads files from SharePoint with Azure AD client credentials"></a>
  <a href="https://github.com/Jeevanvsan/DViewer-Doc"><img src="./assets/card-dviewer.svg" width="49%" alt="DViewer: data aggregation and query platform for many sources in one interface"></a>
</p>

### Activity

<!-- metrics.svg is generated by .github/workflows/metrics.yml; run it once after adding the METRICS_TOKEN secret -->
<img src="./metrics.svg" width="100%" alt="GitHub activity metrics for Jeevanvsan">

<!-- the snake is generated by .github/workflows/snake.yml into the "output" branch -->
<img src="https://raw.githubusercontent.com/Jeevanvsan/Jeevanvsan/output/github-snake.svg" width="100%" alt="Contribution graph being eaten by a snake">

### Connect

<p>
  <a href="https://www.linkedin.com/in/jeevan-varghese-1a5237214/"><img src="./assets/btn-linkedin.svg" height="56" alt="LinkedIn: in/jeevan-varghese-1a5237214"></a>
  <a href="https://jeevan-varghese.blogspot.com"><img src="./assets/btn-blog.svg" height="56" alt="Blog: jeevan-varghese.blogspot.com"></a>
  <a href="mailto:jeevanvsan@gmail.com"><img src="./assets/btn-email.svg" height="56" alt="Email: jeevanvsan@gmail.com"></a>
</p>

<img src="./assets/footer.svg" width="100%" alt="Animated waves of the Alappuzha backwaters">
